CREATE TABLE IF NOT EXISTS addresses (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS emails (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS phones (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL
);